# .github/workflows/callTargetFlow.yml
name: App CI
on:
  push:
    branches: [ main ]

jobs:
  call-deploy:
    uses: rajeshramakrishnan74/shopping-carts/.github/workflows/CalledFromAnotherRepo.yml@main
    with:
      env: sit
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
