# .github/workflows/callTargetFlow.yml
name: CallTarget
on:  workflow_dispatch

jobs:
  call-deploy:
    uses: rajeshramakrishnan74/shopping-carts/.github/workflows/CalledFromAnotherRepo.yml@main
    with:
      env: sit
    secrets:
      ACCESS_KEY_ID: ${{ secrets.GITHUB_TOKEN }}
      SECRET_ACCESS_KEY: ${{ secrets.GITHUB_TOKEN }}
