# .github/workflows/callTargetFlow.yml
name: CallTarget
on:  workflow_dispatch

jobs:
    call-resuable-workflow:
       uses:  rajeshramakrishnan74/shopping-carts/.github/workflows/CalledFromAnotherRepo.yml@54dd2329f1c0090760a2f557ad790c522b2a8461
       with:
           env: '.github/labeler.yml'
       secrets: inherit
