# .github/workflows/callTargetFlow.yml
name: CallTarget
on:  workflow_dispatch

jobs:
  call-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Checkout
        uses: actions/checkout@v5
        with:
          owner: rajeshramakrishnan74
          repository: shopping-carts
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: .github/workflows/CalledFromAnotherRepo.yml
          path:  shopping-carts
    
