# .github/workflows/callTargetFlow.yml
name: CallTarget
on:  workflow_dispatch

jobs:
  call-workflow:
    uses:  rajeshramakrishnan74/shopping-carts/.github/workflows/CalledFromAnotherRepo.yml@main
    secrets: inherit
        
