# .github/workflows/callTargetFlow.yml
name: CallTarget
on:  workflow_dispatch

jobs:
    call-resuable-workflow:
       uses:  rajeshramakrishnan74/shopping-carts/.github/workflows/CalledFromAnotherRepo.yml@e0b3e666f78e8cfa1c05c71dcac03480464d193c 
       with:
           env: 'Path to the config file'
       secrets: 
        personal_access_token: ${{ secrets.TriggerToken }}
