# .github/workflows/callTargetFlow.yml
name: CallTarget
on:  workflow_dispatch

jobs:
  call-deploy:
    uses: rajeshramakrishnan74/shopping-carts/.github/workflows/CalledFromAnotherRepo.yml@main
    with:
      env: sit
    secrets:
       personal_access_token: ${{ secrets.TriggerToken }}
